title: AIEPS
description: This group brings together researchers, practitioners, and students working at the intersection of artificial intelligence and Earth & Planetary Sciences.
theme: jekyll-theme-minimal
